# .github/workflows/ci.yml

name: CI

# Run on pushes and pull requests
on: [push, pull_request]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: 'mobile-app/yarn.lock'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./mobile-app

      - name: Run tests
        run: yarn test --ci --runInBand
        working-directory: ./mobile-app

      - name: Run linter
        run: yarn lint
        working-directory: ./mobile-app

      - name: TypeScript check
        run: yarn typecheck
        working-directory: ./mobile-app